/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicplayer;

import java.io.IOException;
import java.sql.SQLException;

/**
 *
 * @author shiva
 */
public class Music_Player extends javax.swing.JFrame {

    /**
     * Creates new form Music_Player
     */
    private static Listing_Songs ls = null;
    static int playing = 0;
    
    public Music_Player() {
        ls = new Listing_Songs();
        ls.settingplayer();
        initComponents();
        btnStop.setEnabled(false);
        btnPause.setEnabled(false);
        btnResume.setEnabled(false);
        ls.Get_Label(lblSongName);
        ls.Change_Label();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlay = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnPlaylist = new javax.swing.JButton();
        btnSearchPC = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnForward = new javax.swing.JButton();
        btnBackward = new javax.swing.JButton();
        btnResume = new javax.swing.JButton();
        lblSongName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setResizable(false);

        btnPlay.setText("PLAY");
        btnPlay.setPreferredSize(new java.awt.Dimension(50, 30));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnPause.setText("PAUSE");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnPlaylist.setText("PLAYLIST");

        btnSearchPC.setText("SEARCH  PC");
        btnSearchPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPCActionPerformed(evt);
            }
        });

        btnStop.setText("STOP");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnForward.setText(">>");

        btnBackward.setText("<<");

        btnResume.setText("RESUME");
        btnResume.setPreferredSize(new java.awt.Dimension(50, 30));
        btnResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSongName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBackward, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnResume, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnForward, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSearchPC)
                                .addGap(61, 61, 61)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblSongName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPause)
                    .addComponent(btnForward)
                    .addComponent(btnBackward)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchPC)
                    .addComponent(btnPlaylist))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        playing = 1;
        ls.playsong();
        ChangeSongName();
        btnPlay.setEnabled(false);
        btnResume.setEnabled(false);
        btnPause.setEnabled(true);
        btnStop.setEnabled(true);
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnSearchPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPCActionPerformed
        try
        {
            playing = 0;
            ls.stopsong();
            btnPlay.setEnabled(false);
            btnPause.setEnabled(false);
            btnStop.setEnabled(false);
            btnForward.setEnabled(false);
            btnBackward.setEnabled(false);
            btnPlaylist.setEnabled(false);
            btnPrevious.setEnabled(false);
            btnNext.setEnabled(false);
            btnResume.setEnabled(false);
            btnSearchPC.setEnabled(false);
            lblSongName.setText("SEARCHING SONG IN SYSTEM");
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
        SearchinPC spc = new SearchinPC();
        try 
        {
            spc.search();
            btnPlay.setEnabled(true);
            btnPause.setEnabled(true);
            btnStop.setEnabled(true);
            btnForward.setEnabled(true);
            btnBackward.setEnabled(true);
            btnPlaylist.setEnabled(true);
            btnPrevious.setEnabled(true);
            btnNext.setEnabled(true);
            btnResume.setEnabled(true);
            btnSearchPC.setEnabled(true);
            lblSongName.setText("NO SONG IS PLAYING");
        } 
        catch (IOException | SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnSearchPCActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        try
        {
            ls.pausesong();
            playing = 0;
            btnResume.setEnabled(true);
            btnPause.setEnabled(false);
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        try
        {
            ls.stopsong();
            playing = 0;
            btnPause.setEnabled(false);
            btnPlay.setEnabled(true);
            btnResume.setEnabled(false);
            btnStop.setEnabled(false);
        }
        catch(Exception e)
        {
            btnStop.setEnabled(true);
            btnPlay.setEnabled(false);
            btnPause.setEnabled(true);
            btnResume.setEnabled(false);
        }
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(playing == 1)
        {
            ls.nextsong();
            ChangeSongName();
            btnResume.setEnabled(false);
            btnPlay.setEnabled(false);
            btnStop.setEnabled(true);
            btnPause.setEnabled(true);
        }
        else
        {
            ls.nextsong();
            ChangeSongName();
            btnResume.setEnabled(false);
            btnStop.setEnabled(false);
            btnPause.setEnabled(false);
            btnPlay.setEnabled(true);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if(playing == 1)
        {
            ls.previoussong();
            ChangeSongName();
            btnResume.setEnabled(false);
            btnPlay.setEnabled(false);
            btnStop.setEnabled(true);
            btnPause.setEnabled(true);
        }
        else
        {
            ls.previoussong();
            ChangeSongName();
            btnResume.setEnabled(false);
            btnStop.setEnabled(false);
            btnPause.setEnabled(false);
            btnPlay.setEnabled(true);
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumeActionPerformed
        try
        {
            playing = 1;
            ls.resumesong();
            btnPause.setEnabled(true);
            btnPlay.setEnabled(false);
            btnResume.setEnabled(false);
            btnStop.setEnabled(true);
        }
        catch(Exception e)
        {
            btnStop.setEnabled(true);
            btnPlay.setEnabled(false);
            btnPause.setEnabled(false);
            btnResume.setEnabled(true);
        }
    }//GEN-LAST:event_btnResumeActionPerformed

    public void ChangeSongName()
    {
        lblSongName.setText(ls.getsongname());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Music_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Music_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Music_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Music_Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Music_Player().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackward;
    private javax.swing.JButton btnForward;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlaylist;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnResume;
    private javax.swing.JButton btnSearchPC;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblSongName;
    // End of variables declaration//GEN-END:variables
}
